const holdings=[{ticker:'AAPL',name:'Apple Inc.',sector:'Technology',shares:32,avg:156.42,price:182.12,return:16.43,logo:'AP',color:'blue'},{ticker:'NVDA',name:'NVIDIA Corporation',sector:'Technology',shares:45,avg:92.15,price:142.87,return:55.04,logo:'NV',color:'purple'},{ticker:'MSFT',name:'Microsoft',sector:'Technology',shares:18,avg:410.22,price:510.12,return:24.35,logo:'MS',color:'blue'},{ticker:'V',name:'Visa Inc.',sector:'Financials',shares:12,avg:228.40,price:302.45,return:32.36,logo:'VI',color:'red'},{ticker:'JNJ',name:'Johnson & Johnson',sector:'Healthcare',shares:20,avg:161.80,price:179.62,return:11.01,logo:'JN',color:'green'}];
const watch=[{ticker:'NVDA',name:'NVIDIA',price:'$142.87',change:'+3.46%',color:'purple',path:'M0 58 C60 50 75 54 120 39 S190 47 235 20 S280 30 330 7'},{ticker:'MSFT',name:'Microsoft',price:'$510.12',change:'+1.22%',color:'blue',path:'M0 48 C55 55 82 34 125 38 S185 24 225 31 S280 12 330 15'},{ticker:'TSLA',name:'Tesla',price:'$438.42',change:'−0.84%',color:'red',path:'M0 16 C55 20 65 39 110 29 S170 41 215 34 S270 52 330 48'},{ticker:'AMZN',name:'Amazon',price:'$241.08',change:'+2.10%',color:'blue',path:'M0 50 C55 38 75 48 120 28 S190 40 225 21 S285 30 330 8'}];
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function showView(view){$$('.view').forEach(v=>v.classList.remove('active')); const target=$(`#${view}-view`); if(target) target.classList.add('active'); $$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view)); const nav=$(`[data-view="${view}"]`); $('#pageLabel').textContent=nav?nav.textContent.trim().replace(/^\S+\s/,''):view[0].toUpperCase()+view.slice(1); $('#sidebar').classList.remove('open'); window.scrollTo({top:0,behavior:'smooth'});}
function renderHoldings(){ $('#holdingsBody').innerHTML=holdings.map(h=>`<tr><td><div style="display:flex;align-items:center;gap:9px"><span class="stock-logo ${h.color}">${h.logo}</span><div><strong>${h.name}</strong><small class="table-sub">${h.ticker} · ${h.sector}</small></div></div></td><td>${h.shares}</td><td>$${h.avg.toFixed(2)}</td><td>$${h.price.toFixed(2)}</td><td><strong>$${(h.shares*h.price).toLocaleString('en-US',{minimumFractionDigits:2})}</strong></td><td class="positive">+${h.return.toFixed(2)}%</td><td><button class="text-button" data-action="trade">Trade</button></td></tr>`).join('');}
function renderWatch(){ $('#watchGrid').innerHTML=watch.map(w=>`<article class="watch-card"><header><span class="stock-logo ${w.color}">${w.ticker.slice(0,2)}</span><div><h3>${w.name}</h3><small>${w.ticker} · NYSE</small></div><button class="star active">★</button></header><div class="watch-price">${w.price}</div><span class="${w.change[0]==='+'?'positive':'negative'}">${w.change} today</span><svg class="mini-chart" viewBox="0 0 330 65" preserveAspectRatio="none"><path d="${w.path}"/></svg><footer><span>52 week range</span><b>Market open</b></footer></article>`).join('');}
function openTrade(){ $('#tradeModal').hidden=false; } function closeTrade(){ $('#tradeModal').hidden=true; }
$$('.nav-item,[data-view]').forEach(el=>el.addEventListener('click',e=>{const v=el.dataset.view;if(v)showView(v)})); $$('[data-action="trade"]').forEach(el=>el.addEventListener('click',openTrade)); $$('[data-action="add-stock"]').forEach(el=>el.addEventListener('click',()=>alert('Demo action: search for a ticker to add it to your watchlist.'))); $$('[data-close]').forEach(el=>el.addEventListener('click',closeTrade)); $('#tradeModal').addEventListener('click',e=>{if(e.target.id==='tradeModal')closeTrade()}); $('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open')); $('.notice-close').addEventListener('click',e=>e.target.closest('.notice').remove());
renderHoldings();renderWatch();
